name: smarty
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # Localization Library
  flutter_localizations:
    sdk: flutter

  # DI
  provider: ^4.3.2+1

  # Dependency injection
  inject:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject

  # Shared Prefs
  shared_preferences: ^0.5.10

  # Network Agent
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.8
  dio_cookie_manager: ^1.0.0

  # Cookies
  cookie_jar: ^1.0.1

  # Pair and Other Types
  analyzer_plugin: ^0.3.0

  # String validation
  validators: ^2.0.1

  # Retrofit
  retrofit: ^1.3.4

  # Logger
  logger: any

  # Streams and RX
  rxdart: ^0.24.1

  # ORM, Database SQL
  sqfentity: ^1.4.0+1

  # Firebase Libs
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  cloud_firestore: ^0.14.0+2

  # Localization
  gen_lang: 0.1.3

  # Internationalization
  intl: ^0.16.1

  # Toasts
  fluttertoast: ^7.0.4

  # Carousel Slider
  carousel_slider: ^2.2.1

  # Audio Player
  just_audio: ^0.4.0
  audio_manager: ^0.5.5+3

  # Video Player
  video_player: ^0.10.12+2
  flick_video_player: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1

  country_pickers: ^1.3.0
  inject_generator:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject_generator

  # Generate Language Files
  lang_table: 0.2.0


flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
